### ISSUE TITLE
Also apply to tooltips of clicked recipe itemlinks!

### ISSUE THREAD

**Issue by LudiusMaximus** [LudiusMaximus/TidyRecipeTooltip#1]

**Comment by Sluimerstand** [comment]
![image](https://github.com/LudiusMaximus/TidyRecipeTooltip/assets/29845810/9730ceeb-5646-4798-bf61-66322aabb92e)
Seems to be working by now. :D

**Comment by LudiusMaximus** [comment]
Thanks for pointing this out! :-)
