### ISSUE TITLE
Missing localization phrase, perhaps?+

### ISSUE THREAD

**Issue by Myrroddin** [LudiusMaximus/TidyRecipeTooltip#2]
Whenever one of my characters cannot learn a recipe, I keep getting "TidyRecipeTooltip: Could not finde "Use: Teaches you..."  line printed to chat. Not only is the phrase missing, "find" is misspelled.
![TidyRecipeTooltip could not find error](https://user-images.githubusercontent.com/6456346/91969509-6da4e880-ecd3-11ea-8776-933f249e84aa.jpg)

**Comment by LudiusMaximus** [comment]
All right. The "finde" ist just a typo. :-) Thanks, anyway!

But the error itself: are you using any other addons that modify the tooltip.
What my addon does is to scan the tooltip for the "Use: Teaches you..." line.

I see you are using a different font, so maybe your tooltip lines do not directly start with ITEM_SPELL_TRIGGER_ONUSE.

You could do me a favour and try to replace
searchPattern = "^" .. ITEM_SPELL_TRIGGER_ONUSE .. ".-" .. teachesYouString[locale]
with
searchPattern = "^.-" .. ITEM_SPELL_TRIGGER_ONUSE .. ".-" .. teachesYouString[locale]

(Don't be confused that there is one and the same line for Korean and Non-Korean. This is sill an artifact I have to remove...)

**Comment by Myrroddin** [comment]
Right, I made the change, and did some more testing. I still get the message in chat, but good news! The message is printed from recipes that used to exist but have been turned into grey trash items. I'm thinking TRT's list of itemIDs include the various recipes that have been turned into Charred Recipe instead, along with Ancient Enchanting Vellum. Thus far, I have found 4 itemIDs that are grey trash, and TRT is still checking those for the phrase. Of course, the addon won't find the phrase.

That means the easy fix is search Wowhead for Recipes > Available to players - no > grey quality. Those will be all your invalid itemIDs. Here is the complete list:
[](https://www.wowhead.com/poor-recipe-items?filter=161;2;0)

**Comment by Myrroddin** [comment]
Edit: the list also includes recipes that can be bought sold, and learned, but the source in the game that provided the recipe has been removed. That means any quality of recipe that is flagged as unavailable triggers that message to chat. Here is the revised list:

- https://www.wowhead.com/recipe-items/quality:0:1:2:3:4:5:6:7:8?filter=161;2;0

**Comment by LudiusMaximus** [comment]
Ah, nice! Thanks for your investigations. Luckily I am using https://www.wowace.com/projects/librecipes-3-0 in which I can directly check if a recipe teaches nothing. I am putting out a new release momentarily.
