### ISSUE TITLE
Could not find money line. If this behaviour is reproducible, please contact the developer!

### ISSUE THREAD

**Issue by Sluimerstand** [LudiusMaximus/TidyRecipeTooltip#4]
I daresay I found a rather reliable way to reproduce this.
![image](https://github.com/LudiusMaximus/TidyRecipeTooltip/assets/29845810/6da4ad51-b039-4521-aa62-290c3a77cf56)

It happens when hovering over an Auction House listing of a recipe, like this:
![image](https://github.com/LudiusMaximus/TidyRecipeTooltip/assets/29845810/4c06bef0-fe15-46e1-807b-5c07e68f2917)

It makes sense since the AH tooltip, at least natively, omits the vendor price entirely. It also seems to append its own AH info (Seller, Time Left) after other AddOn tooltip lines, which is interesting (and possibly annoying in using those lines instead of a sell price line to make your code do what it does). Anyway, I hope this helps. :)

**Comment by LudiusMaximus** [comment]
I thinkthis is fixed with the new version 2.1.1. Let me know if you still get it.
